version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"
    commit-message:
      prefix: "build: "
      include: "scope"
