name: simple_flashcards
description: Minimalistic flashcards app for all platforms
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  adaptive_dialog: ^2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.0.4
  intl: ^0.18.1
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  package_info: ^2.0.2
  url_launcher: ^6.2.6
  dynamic_color: ^1.7.0
  fast_csv: ^0.2.10
  emoji_picker_flutter: ^2.1.0
  shared_preferences: ^2.0.15
  text_to_speech: ^0.2.3
  chat_gpt_sdk: ^2.2.5
  file_picker: ^8.0.3
  share_plus: ^7.2.1
  chat_bubbles: ^1.5.0
  flip_card: ^0.7.0
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.1
  import_sorter: ^4.6.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
